---
title: Port Macquarie Tender Centre
timezone: Australia/Sydney
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
locale: en-AU
encoding: utf-8
email: hello@pmtc.com.au
description: You deliver the goods, we deilver the customer!
baseurl: 
url: https://www.pmtc.com.au
markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md
gems:
- jekyll-email-protect
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
