---
title: Port Macquarie Tender Centre
timezone: Australia/Sydney
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@pmtc.com.au
url: https://www.pmtc.com.au
description: You deliver the goods, we deilver the customer!
keywords: buy, sell, secondhand, second-hand, port macquarie, furniture, tools
locale: en-AU
encoding: utf-8
contact: static
color:
  primary: 18bc9c
  primary-rgb: '24,288,156'
  secondary: 2c3e50
  secondary-dark: 233140
footer:
  copyright: Port Macquarie Tender Centre
  location: Location
  social: Around the Web
  credits: Credits
social:
- title: twitter
  url: https://twitter.com/_tendercentre
- title: facebook
  url: https://facebook.com/tendercentre
- title: instagram
  url: https://instagram.com/tendercentre
address:
- line: 14-17/35 Merrigal Road
- line: Port Macquarie, NSW 2444
credits: Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start
  Bootstrap</a>.
markdown: kramdown
highlighter: rouge
markdown_ext: markdown,mkdown,mkdn,mkd,md
permalink: pretty
gems:
- jekyll-email-protect
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
