---
title: Port Macquarie Tender Centre
timezone: Australia/Sydney
lang: en_AU
description: You deliver the goods, we deilver the customer!
baseurl: ''
url: https://www.pmtc.com.au
logo: /img/apple-touch-icon.png
google_site_verification: iXb5Sz5oiviaDDdXK4XLslgGBSfzahNlJjdPvaMYCG4
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@pmtc.com.au
twitter:
  username: _tendercentre
facebook:
  publisher: https://www.facebook.com/TenderCentre/
markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md
highlighter: rouge
permalink: pretty
sass:
  sass_dir: _sass
  style: compressed
exclude:
- ".gitignore"
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE
- README.*
- vendor
- node_modules
plugins:
- jekyll-email-protect
- jekyll-sitemap
- jekyll-seo-tag
