---
title: Port Macquarie Tender Centre
timezone: Australia/Sydney
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@pmtc.com.au
description: You deliver the goods, we deilver the customer!
address:
- line: 14-17/35 Merrigal Road
- line: Port Macquarie, NSW 2444
encoding: utf-8
locale: en-AU
baseurl: 
url: https://www.pmtc.com.au
twitter_username: _tendercentre
markdown: kramdown
highlighter: rouge
markdown_ext: markdown,mkdown,mkdn,mkd,md
permalink: pretty
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-email-protect
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
