---
title: Port&nbsp;Macquarie Tender&nbsp;Centre
timezone: Australia/Sydney
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
lang: en_AU
description: You deliver the goods, we deilver the customer!
baseurl: ''
url: https://www.pmtc.com.au
logo: "/img/apple-touch-icon.png"
google_site_verification: iXb5Sz5oiviaDDdXK4XLslgGBSfzahNlJjdPvaMYCG4
email: hello@pmtc.com.au
twitter:
  username: _tendercentre
facebook:
  publisher: https://www.facebook.com/TenderCentre/
exclude:
- Gemfile
- Gemfile.lock
- gulpfile.js
- node_modules
- package.json
- package-lock.json
- README.md
- src
- tailwind.js
- yarn.lock
plugins:
- jekyll-email-protect
- jekyll-sitemap
- jekyll-seo-tag
