# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Port Macquarie Tender Centre
email: hello@pmtc.com.au
description: You deliver the goods, we deilver the customer!
address:
- line: 14-17/35 Merrigal Road
- line: Port Macquarie, NSW 2444
timezone: Australia/Sydney
encoding: utf-8
locale: en-AU
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.pmtc.com.au # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _tendercentre
# github_username:  jekyll

# Build settings
markdown: kramdown
highlighter: rouge
markdown_ext: markdown,mkdown,mkdn,mkd,md
permalink: pretty
theme: minima
plugins:
- jekyll-email-protect
- jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
 - Gemfile
 - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
